# permissions for end users to view webinstalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webinstall-viewer-role
rules:
- apiGroups:
  - crd.bartam
  resources:
  - webinstalls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.bartam
  resources:
  - webinstalls/status
  verbs:
  - get
