name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  test_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build
        run: make manager

      - name: Test
        run: echo "no test"

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bartam1/kubopwebdep
          tag_with_ref: true