name: ci

on:
  push:
    branches: master

jobs:
  test_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build
        run: make manager

      - name: Test
        run: echo "no test"
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Build image 
        run:  docker build . -t bartam1/kubopwebdep:latest

      - name:  Push image to docker hub
        run: docker push  bartam1/kubopwebdep:latest
      
        